### ISSUE TITLE
Failed to load script

### ISSUE THREAD

**Issue by mhdfadlyhasan** [csrausyan/csrausyan.github.io#1]
https://media.discordapp.net/attachments/881094584229322802/897854220902989864/unknown.png

**Comment by irshadrasyidi** [comment]
I think its bcs the owner didnt push index.js from the boilerplate he got from gugel
![image](https://user-images.githubusercontent.com/36858141/137155658-7b606ff6-e796-4f16-b3f1-21d99423106a.png)

**Comment by mhdfadlyhasan** [comment]
> I think its bcs the owner didnt push index.js from the boilerplate he got from gugel ![image](https://user-images.githubusercontent.com/36858141/137155658-7b606ff6-e796-4f16-b3f1-21d99423106a.png)

thank you irshad but i think nobody can fix it,  enjoy this doge
![Doge](https://c.tenor.com/Yar0zKi_W6IAAAAC/doge.gif)
